DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    LastName VARCHAR(255) NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    UserName VARCHAR(255) NOT NULL,
    Password VARCHAR(255),
    City VARCHAR(255) NOT NULL,
    Email VARCHAR(255),
    Icon VARCHAR(255),
);
