DROP TABLE IF EXISTS PACKAGES;

CREATE TABLE Packages (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    CharityName VARCHAR(255) NOT NULL,
    Category VARCHAR(255) NOT NULL, 
    Description VARCHAR(255) NOT NULL,
    City VARCHAR(255) NOT NULL,
    NumberDonations INTEGER NOT NULL,
);
